### ISSUE TITLE
[FEATURE] - Prompts for Scouting Maps and Heirlooms

### ISSUE THREAD

**Issue by Zenjir0** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#123]
### Description

Basically when you create a new character, have a check in place to see if the player already owns any of the "Scouting Map" Toys and request that they activate them for the route they are taking. 

Same for heirloom items. It should perform a check and recommend to equip the item if available.  

### Solution

This can speed things up slightly by activating most if not all of the flight points for each location and when they go to a flight point for the first time it should cache all the known locations so you don't have to go to each flight point when prompted in the route. It should just skip those steps since the toy activates all of them for you.

### Alternative solutions

N/A

**Comment by julien-lanctot** [comment]
The scouting map one feels like a nightmare code wise, would require rethinking all or most of the routes.  The heirloom one seems feasible.

**Comment by Neogeekmo** [comment]
Feature available in the next version (v3.1) 

I've added a frame with all the available maps + a shortcut button to the heirloom frame (you'll have to select them yourself, otherwise there's too much dependency on the classes and what's available)

This frame will appear by default for everyone, with a close button and the option to reopen it in the options
