### ISSUE TITLE
[FEATURE] - Adding a max level/no longer needing to level option

### ISSUE THREAD

**Issue by Nigok** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#142]
### Description

i like using APR even at max level just for the auto skip cutscenes, auto sell grays, auto repairs and even auto accept/turn in quests and sometimes have issues with it still showing the quest list at max level and it telling me what i should do so i have to pull the window sort of off screen.

### Solution

just adding a box you could tick that indicates that you are max level so it gets rid of all leveling paths (simply removing everything from the custom path does not really do anything in most cases)

### Alternative solutions

adding a box you could tick indicating you no longer want to level

**Comment by Neogeekmo** [comment]
I do not understand your request, on my character lvl 70 I have my custom path empty, I disabled the display of the quest order list;  I have only the currents step enabled but as my custom path is empty it is not displayed

Otherwise you can just hide it in the options ⬇️ (blue one)

![image](https://github.com/Rycia/azeroth-pilot-reloaded/assets/28711160/ebe69bda-34de-4ab0-a469-c559eef58f9e)
(sorry the screens are in french but the position are the same)

**Comment by Nigok** [comment]
it kind of depends on the zone cause when im on my max levels its fine in zones like orgrimmar and the whole DF expansion but stuff like BFA i still get the quest list and recently when i went over to just do some story quests it started freaking out and kept sort of resetting the list and what i had to do and skipping the part did nothing as it also was spamming my chat

**Comment by Neogeekmo** [comment]
If you experienced this issue in versions 2.3.0 to 2.3.3, we had some issues with my new feature to pinkup quests from routes.
If you're still encountering it in version 2.3.4, it means your custom path is not empty. 
So, we have an option to pickup all quests or only those from routes (if the route is empty, it pickup all quests).

I'll run a test to see if I encounter any issues with my max level characters in BFA. If that's the case, it's more likely a bug rather than a feature.

**Comment by Nigok** [comment]
The part that specifically was spamming my chat log was the war campaign when going to tirangarde sound from the horde side specifically and my custom path was in fact empty as well as quest list turned off if any of that would be of help. But the main part of the post would just be adding an option to like sieze all quest paths and whatnot so you wouldn't have to go turn everything off from custom path to ques list

**Comment by Nigok** [comment]
the version i was on was 2.3.4 also

**Comment by Neogeekmo** [comment]
I don't agree with you, I use it like him but I don't have his problems so I try to understand, 
and it avoids me to have a lot of addon when the one I dev already does everything I need

**Comment by julien-lanctot** [comment]
I agree with @Pahonix  on this, seems silly to add features that other addons do better.  Think we can close this
