### ISSUE TITLE
[ISSUE] - Quest names not showing up

### ISSUE THREAD

**Issue by burntorangejedi** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#143]
### Description

When APR opens, there is a lot of stuff for me to do, but none of the quest names are showing up. Is there a dependency I'm missing somewhere?

### APR Version

APR 2.3.4

### APR Route

Speedrun

### World of Warcraft Flavor

Retail (Default)

### Tested with only APR

- [X] Yes
- [ ] No

### Lua Error

```true
None
```

### Reproduction Steps

1. Log in to character in Burning Crusade on Chromie Time
2. Observe

### Last Good Version

No previous version tried

### Screenshots

![image](https://github.com/Rycia/azeroth-pilot-reloaded/assets/125756530/4d1af061-fa6c-42bd-bc92-6cd9fa5ba756)

**Comment by Pahonix** [comment]
The quest names are not available to the addon until you have seen them the first time. On subsequent play throughs, the addon will have cached the quest names and will be able to display them in the QuestOrderList.

**Comment by burntorangejedi** [comment]
Thanks for answering my question, but perhaps, as a feature recommendation, you could add Grail support so that the names are available from the start?

**Comment by NightofStarrs** [comment]
This is something that can be looked at in the future (possible for version 3). The issue was, we did not want to have a list of quest names to iterate over, thus the addon runs solely on the QuestID of the quest (or intractable object), and then the quest parts/path. This was done originally to save space, and processing power, but the addon is written to display the QuestID and Quest Name once it has been set up in your WoW Cache folder, thus relying on you having previously interacted with the quest at some time in the past (on a previous character).

APR (and the predecessor) AAP were designed for Alt Leveling, by taking the guess work out of leveling additional characters, not for a first time play through.

**Comment by NightofStarrs** [comment]
We are going to look into using Grail, but we need to evaluate the addon, and see if we can hook into it, or if we need to have it side-loaded with APR. I will go ahead and close this for now, and instead change it into a Feature Request instead of an Issue.
