### ISSUE TITLE
[FEATURE] - Auto-use Flight Paths to OFF by default

### ISSUE THREAD

**Issue by palanthis** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#153]
### Description

Could you please... Pretty please, ship with Auto-Use Flight Paths to off? I level a LOT of alts, but I also leave APR running on my max level toons for the automation. Any time I have to do a /forcereset, the next time I log in to one of my max level toons and talk to a flight master, there I go, flying to Light knows where.

### Solution

Ship the addon with the feature turned off by default. You could add a dialog option on first login, where you have already added First Character, for "Full Automation" or something like that.

### Alternative solutions

Allow the creation of a profiles, which can store that saved variable. I would love to be able to modify a "default" profile so that all new toons have flight off, repair on, vendor grey on, etc.

**Comment by Pahonix** [comment]
We are very unlikely to ship with any of the automation features defaulted to off. That is the whole point of the addon. Just because one of the features inconveniences your max level toons that are not using the addon for its intended purpose does not justify modifying the addon for everyone else.

v3 of the addon will hopefully support profiles like you suggest and you can set up a profile to configure it to your liking.

**Comment by julien-lanctot** [comment]
I think we can safely close this with @Pahonix comment, feels like a niche case.

**Comment by NightofStarrs** [comment]
As Pahonix indicated, you can hold down Control to stop _ANY_ of the automated actions, such as cut-scene skipping, flight paths, and picking up/handing in quests.

APR's Forcereset command as it is currently written removes (overwrites) your savedvariable file which APR pulls from with null, so that way it can all be freshy loaded again. In V3 this will be changed to be more dynamic and more control over what to reset and how. And, as mentioned, we are looking into and planning to have some sense of a profile based option, which will include all of the Automatic actions and their set On/Off preference, as well as the route(s) you wish to go through.

At this current time, I will go ahead and close this request, as it is something we are not looking into enabling as a default (Off) option.
