### ISSUE TITLE
[ISSUE] - 

### ISSUE THREAD

**Issue by SwiftDeth13** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#159]
### Description

using as normal but after 5 quests it gives error: "Apr: not yet!". The only function of AAP is that it accepts and turns in quests, and it has not been doing so recently. i have reinstalled, updated.

### APR Version

APR-v2.4.0.zip

### APR Route

first character

### World of Warcraft Flavor

Retail (Default)

### Tested with only APR

- [X] Yes
- [ ] No

### Reproduction Steps

?

**Comment by Pahonix** [comment]
The "Not Yet" response is when you try to accept a quest that APR is not expecting you to accept, i.e., not part of the route step you are currently on. 

In order to troubleshoot further, we would need to know exactly where you are in the route. Can you provide a screenshot of your Custom Path screen (/apr > Custom Path) and a screenshot of your QuestOrderList (if not visible, you can enable this in the /apr settings).

**Comment by Neogeekmo** [comment]
The only function of **APR** is more than just accepting and returning quests.

Since v2.3.0 APR has as default option to take only the quests of the current step, if you want to take all the quests, I invite you to do `/apr` and enable `Accept the quest(s)`
