### ISSUE TITLE
[ISSUE] - Remix fails to function properly

### ISSUE THREAD

**Issue by jsauerland** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#278]
### Description

I picked the Azeroth Auto Pilot 'MOP Remix' trail, and it keeps sending me to quests I've completed, or to turn in things that don't exist. Why is it doing this? Example shown below. Turn in the quest. 1/1.... I have no quest. I've been done with Jade forest for 5 hours. 

![image](https://github.com/Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded/assets/32148757/261c9c0b-08a5-42f5-92fe-4146b76a5ee2)

### World of Warcraft Flavor

Retail (Default)

### APR Status

```lua
{
{"Class","MAGE"},
{"Continent","Pandaria"},
{"Time & Date","Sat May 18 08:28:56 2024"},
{"Language","enUS"},
{"Name","Ravenoria"},
{"Realm","Moon Guard"},
{"World Coordinates"," -1685.60, 2484.70"},
{"Level","39"},
{"AddOn Version","v3.2.0"},
{"Faction","Horde"},
{"Coordinates","44.93, 25.08"},
{"Client Build","54762"},
{"Client Version","10.2.7"},
{"Step","289, Done"},
{"Route","371-The Jade Forest"},
{"Zone","The Jade Forest"}
}
```
### Tested with only APR

- [X] Yes
- [ ] No

### Reproduction Steps

1. Log into any character partially through the MOP Remix
2. Choose MOP Remix path

**Comment by NightofStarrs** [comment]
So, I had noticed a few times personally that the UI element is not progressing correctly, either doesn't register something had finished or that I am not at that actual step.

Can you do two things, enable the Quest Order List: ![Quest Order List being enabled in APR Settings.](https://i.imgur.com/SLUcPHY.png)

As well, also do an `/apr forcereset` and see if anything changes?

Mainly, your Status output marks your last step 289 as DONE, while the UI element for steps only has 288 with a turn in quest.

**Comment by NightofStarrs** [comment]
Also, question, @jsauerland 

> Reproduction Steps
> 
> 1. Log into any character partially through the MOP Remix
> 2. Choose MOP Remix path

---

Is this from you already starting a character through MoP Remix, and then enabling APR's MoP Remix route? Because our routes are very specific, this also can happen as well - where it is sending you somewhere after the fact because you are now phased/too far in the quest chain to grab a breadcrumb or it just may not have triggered that it had been completed previously.

It's usually advised to start with APR being on, as it always has trouble trying to sync up to where you are, especially if you just follow random quest chains.

**Comment by Neogeekmo** [comment]
First thing you can do, is to update your Addon, you are in version 3.2.0, while there is version 3.2.3 with fixes on the routes

**Comment by jsauerland** [comment]
Thanks @NightofStarrs and @Neogeekmo. I followed your advice/instructions... seems to work just fine now 👍
